'use client'

import { useState } from 'react'
import { Download, Calendar, FileText, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

interface ItineraryExportProps {
  itinerary: {
    id: string
    title: string
    country: string
    location: string
    budget: number
    currency: string
    days: number
    travelType: string
    status: string
    departureDate?: Date | string
    returnDate?: Date | string
    requirements?: string
    activities?: string
    days_plan?: Array<{
      dayNumber: number
      date?: Date | string
      activities: Array<{
        title: string
        time: string
        location: string
        notes?: string
      }>
    }>
  }
}

export function ItineraryExport({ itinerary }: ItineraryExportProps) {
  const [exporting, setExporting] = useState<'pdf' | 'ics' | null>(null)

  // Export to PDF
  const exportPDF = async () => {
    setExporting('pdf')
    
    try {
      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()

      // Header
      doc.setFillColor(255, 107, 107)
      doc.rect(0, 0, pageWidth, 45, 'F')
      
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(24)
      doc.text('Travereel', 14, 18)
      
      doc.setFontSize(20)
      doc.text(itinerary.title, 14, 32)
      
      doc.setFontSize(10)
      doc.text(`${itinerary.location}, ${itinerary.country}`, 14, 40)

      // Trip Details
      doc.setTextColor(0, 0, 0)
      doc.setFontSize(12)
      doc.text('Trip Details', 14, 58)

      const details = [
        ['Destination', `${itinerary.location}, ${itinerary.country}`],
        ['Duration', `${itinerary.days} days`],
        ['Travel Type', itinerary.travelType],
        ['Status', itinerary.status],
        ['Budget', `${itinerary.currency} ${itinerary.budget.toLocaleString()}`],
      ]

      if (itinerary.departureDate) {
        details.push(['Departure', format(new Date(itinerary.departureDate), 'MMM dd, yyyy')])
      }
      if (itinerary.returnDate) {
        details.push(['Return', format(new Date(itinerary.returnDate), 'MMM dd, yyyy')])
      }

      autoTable(doc, {
        startY: 62,
        head: [['Detail', 'Information']],
        body: details,
        theme: 'striped',
        headStyles: {
          fillColor: [255, 107, 107],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        styles: {
          fontSize: 10,
          cellPadding: 5,
        },
      })

      // Daily Itinerary
      if (itinerary.days_plan && itinerary.days_plan.length > 0) {
        const finalY = (doc as any).lastAutoTable.finalY + 10
        
        doc.setFontSize(14)
        doc.text('Daily Itinerary', 14, finalY)

        itinerary.days_plan.forEach((day, index) => {
          const dayY = index === 0 ? finalY + 10 : (doc as any).lastAutoTable?.finalY + 10
          
          // Check if we need a new page
          if (dayY > 250) {
            doc.addPage()
            doc.setFontSize(14)
            doc.text('Daily Itinerary (continued)', 14, 15)
          }

          doc.setFontSize(12)
          doc.setTextColor(255, 107, 107)
          doc.text(`Day ${day.dayNumber}`, 14, dayY + (index === 0 ? 0 : 5))
          
          doc.setTextColor(0, 0, 0)

          const activitiesData = day.activities.map(activity => [
            activity.time,
            activity.title,
            activity.location,
            activity.notes || '-',
          ])

          autoTable(doc, {
            startY: dayY + (index === 0 ? 8 : 13),
            head: [['Time', 'Activity', 'Location', 'Notes']],
            body: activitiesData,
            theme: 'grid',
            headStyles: {
              fillColor: [46, 196, 182],
              textColor: [255, 255, 255],
              fontStyle: 'bold',
            },
            styles: {
              fontSize: 9,
              cellPadding: 4,
            },
          })
        })
      }

      // Requirements
      if (itinerary.requirements) {
        const reqY = (doc as any).lastAutoTable?.finalY + 10 || 200
        
        if (reqY > 250) {
          doc.addPage()
        }

        doc.setFontSize(12)
        doc.text('Travel Requirements', 14, reqY)
        
        doc.setFontSize(10)
        doc.setTextColor(80, 80, 80)
        const splitText = doc.splitTextToSize(itinerary.requirements, pageWidth - 28)
        doc.text(splitText, 14, reqY + 8)
      }

      // Footer
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(
        `Generated by Travereel on ${format(new Date(), 'MMM dd, yyyy HH:mm')}`,
        14,
        doc.internal.pageSize.getHeight() - 10
      )

      // Save
      doc.save(`travereel-${itinerary.title.replace(/\s+/g, '-').toLowerCase()}.pdf`)
      toast.success('PDF exported successfully!')
    } catch (error) {
      console.error('PDF export error:', error)
      toast.error('Failed to export PDF')
    } finally {
      setExporting(null)
    }
  }

  // Export to ICS Calendar
  const exportICS = async () => {
    setExporting('ics')
    
    try {
      let icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Travereel//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:${itinerary.title}
`

      if (itinerary.days_plan) {
        itinerary.days_plan.forEach((day) => {
          day.activities.forEach((activity) => {
            const eventDate = day.date || itinerary.departureDate
            
            if (eventDate) {
              const startDate = new Date(eventDate)
              const [hours, minutes] = activity.time.split(':').map(Number)
              startDate.setHours(hours, minutes, 0)
              
              const endDate = new Date(startDate)
              endDate.setHours(endDate.getHours() + 1) // Default 1 hour duration

              const formatICSDate = (date: Date) => {
                return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
              }

              icsContent += `BEGIN:VEVENT
DTSTART:${formatICSDate(startDate)}
DTEND:${formatICSDate(endDate)}
SUMMARY:${activity.title}
LOCATION:${activity.location}
DESCRIPTION:${activity.notes || ''}
STATUS:CONFIRMED
END:VEVENT
`
            }
          })
        })
      }

      icsContent += 'END:VCALENDAR'

      // Download
      const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${itinerary.title.replace(/\s+/g, '-').toLowerCase()}.ics`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)

      toast.success('Calendar file exported! Import it to your calendar app.')
    } catch (error) {
      console.error('ICS export error:', error)
      toast.error('Failed to export calendar')
    } finally {
      setExporting(null)
    }
  }

  return (
    <div className="flex gap-2">
      <Button
        onClick={exportPDF}
        disabled={exporting !== null}
        size="sm"
        className="flex-1 bg-gradient-to-r from-[#FF6B6B] to-[#FF8C42] text-white hover:opacity-90"
      >
        {exporting === 'pdf' ? (
          <Loader2 className="size-4 mr-2 animate-spin" />
        ) : (
          <FileText className="size-4 mr-2" />
        )}
        Export PDF
      </Button>

      <Button
        onClick={exportICS}
        disabled={exporting !== null}
        size="sm"
        variant="outline"
        className="flex-1 border-[#2EC4B6] text-[#2EC4B6] hover:bg-[#2EC4B6]/5"
      >
        {exporting === 'ics' ? (
          <Loader2 className="size-4 mr-2 animate-spin" />
        ) : (
          <Calendar className="size-4 mr-2" />
        )}
        Calendar
      </Button>
    </div>
  )
}
